spring.application.name=notification-service
server.port=${PORT:8082}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:notification_service}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
logging.level.root=INFO
logging.level.com.jobportal=DEBUG
logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
resend.api.key=${RESEND_API_KEY}