spring.application.name=notification-service
server.port=${PORT:8082}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:notification_service}
logging.level.root=INFO
logging.level.com.jobportal=DEBUG
logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
brevo.api.key=${BREVO_API_KEY:}
mail.from=${MAIL_FROM:}
